Partially revert auditing bean registration changes.
Restoring bean registration while keeping the optional nature of AuditorAware in the Reactive-/AuditingHandler.

The changes done previously caused AOT code generation to fail with:
org.springframework.aot.generate.UnsupportedTypeValueCodeGenerationException: Code generation does not support org.springframework.beans.factory.config.AutowiredPropertyMarker

See: #3177