DATACMNS-624 - Re-activated Travis builds for spring4, spring41, spring41-next and querydsl-next.
Also activated building on the new container infrastructure to use artifact caching.

Removed JDK 6 and 7 builds as the build on these VMs will fail due to the Optional stub causing NoClassDefFoundErrors.