DATACMNS-1802 - Extract Flux.from(…) into own method.
For some reason, calling Flux.from(…) in its own, static method, heals NoClassDefFoundError even though the method is not used during runtime nor Publisher is defined in a method signature.